version: '3.8'

services:
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"

  # backend:
  #   build: ./backend
  #   ports:
  #     - "3001:3001"

  # ml-service:
  #   build: ./ml-service
  #   ports:
  #     - "8000:8000"

  # db:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: insurancedb
  #   ports:
  #     - "5432:5432"
