"""
Train and compare classification models for insurance claim fraud detection.

Combines numeric features (amount, days_since_policy_start, has_witnesses,
prior_claims_count, one-hot encoded claim_type) with text features extracted
from the claim description via TF-IDF (bag-of-words + bigrams).

Pipeline:
    1. Load synthetic dataset (generated by generate_fraud_dataset.py).
    2. Stratified train/test split (80/20).
    3. Two feature configurations are evaluated to demonstrate the value of
       the text channel:
        (a) Numeric-only baseline.
        (b) Numeric + TF-IDF text features.
       For each configuration, three classifiers are trained:
       LogisticRegression, RandomForestClassifier, HistGradientBoostingClassifier.
    4. Evaluation on the held-out test set: precision, recall, F1, ROC-AUC,
       confusion matrix.
    5. Save the best overall (highest ROC-AUC) pipeline to ../models/fraud_model.joblib.
    6. Generate ROC curves and confusion matrix plots; print a comparison table.

Usage:
    python training/train_fraud_model.py
"""

import os
import json
import joblib
import numpy as np
import pandas as pd
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, HistGradientBoostingClassifier
from sklearn.metrics import (
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    roc_curve,
    classification_report,
)

HERE = os.path.dirname(__file__)
DATA_PATH = os.path.join(HERE, "..", "data", "fraud_dataset.csv")
MODEL_PATH = os.path.join(HERE, "..", "models", "fraud_model.joblib")
METRICS_PATH = os.path.join(HERE, "..", "models", "fraud_model_metrics.json")
PLOTS_DIR = os.path.join(HERE, "plots")

NUMERIC_FEATURES = ["amount", "days_since_policy_start", "has_witnesses", "prior_claims_count"]
CATEGORICAL_FEATURES = ["claim_type"]
TEXT_FEATURE = "description"
TARGET = "is_fraud"

RANDOM_STATE = 42


def build_preprocessor(include_text: bool) -> ColumnTransformer:
    """Build a ColumnTransformer with optional TF-IDF on the description."""
    transformers = [
        ("num", StandardScaler(), NUMERIC_FEATURES),
        ("cat", OneHotEncoder(handle_unknown="ignore"), CATEGORICAL_FEATURES),
    ]
    if include_text:
        transformers.append(
            (
                "text",
                TfidfVectorizer(
                    max_features=500,
                    ngram_range=(1, 2),
                    stop_words="english",
                    min_df=2,
                ),
                TEXT_FEATURE,
            )
        )
    return ColumnTransformer(transformers=transformers, remainder="drop")


def build_classifiers():
    return {
        "Logistic Regression": LogisticRegression(
            max_iter=1000, class_weight="balanced", random_state=RANDOM_STATE
        ),
        "Random Forest": RandomForestClassifier(
            n_estimators=200,
            max_depth=15,
            class_weight="balanced",
            random_state=RANDOM_STATE,
            n_jobs=-1,
        ),
        "Gradient Boosting": HistGradientBoostingClassifier(
            max_iter=300,
            max_depth=6,
            learning_rate=0.05,
            class_weight="balanced",
            random_state=RANDOM_STATE,
        ),
    }


def evaluate(model, X_test, y_test) -> tuple[dict, np.ndarray]:
    y_pred = model.predict(X_test)
    y_proba = model.predict_proba(X_test)[:, 1]
    return (
        {
            "precision": precision_score(y_test, y_pred, zero_division=0),
            "recall": recall_score(y_test, y_pred, zero_division=0),
            "f1": f1_score(y_test, y_pred, zero_division=0),
            "roc_auc": roc_auc_score(y_test, y_proba),
            "confusion_matrix": confusion_matrix(y_test, y_pred).tolist(),
        },
        y_proba,
    )


def plot_roc_curves(results: dict, y_test, save_path: str):
    plt.figure(figsize=(8, 6))
    for label, r in results.items():
        fpr, tpr, _ = roc_curve(y_test, r["y_proba"])
        auc = r["metrics"]["roc_auc"]
        plt.plot(fpr, tpr, label=f"{label} (AUC = {auc:.3f})", linewidth=2)
    plt.plot([0, 1], [0, 1], "k--", linewidth=1, alpha=0.5, label="Random (AUC = 0.500)")
    plt.xlabel("False Positive Rate", fontsize=12)
    plt.ylabel("True Positive Rate", fontsize=12)
    plt.title("ROC Curves — Insurance Fraud Detection", fontsize=14, fontweight="bold")
    plt.legend(loc="lower right", fontsize=9)
    plt.grid(alpha=0.3)
    plt.tight_layout()
    plt.savefig(save_path, dpi=120)
    plt.close()


def plot_confusion(cm: list, model_name: str, save_path: str):
    cm_arr = np.array(cm)
    fig, ax = plt.subplots(figsize=(6, 5))
    im = ax.imshow(cm_arr, cmap="Reds")
    classes = ["Legitimate", "Fraudulent"]
    ax.set_xticks([0, 1])
    ax.set_yticks([0, 1])
    ax.set_xticklabels(classes)
    ax.set_yticklabels(classes)
    ax.set_xlabel("Predicted", fontsize=12)
    ax.set_ylabel("Actual", fontsize=12)
    ax.set_title(f"Confusion Matrix — {model_name}", fontsize=14, fontweight="bold")
    for i in range(2):
        for j in range(2):
            ax.text(
                j, i, str(cm_arr[i, j]),
                ha="center", va="center", fontsize=18,
                color="white" if cm_arr[i, j] > cm_arr.max() / 2 else "black",
                fontweight="bold",
            )
    plt.colorbar(im)
    plt.tight_layout()
    plt.savefig(save_path, dpi=120)
    plt.close()


def main():
    print(f"Loading dataset from {DATA_PATH}")
    df = pd.read_csv(DATA_PATH)
    print(f"  -> {len(df):,} rows, {df[TARGET].mean():.1%} positive class\n")

    feature_cols = NUMERIC_FEATURES + CATEGORICAL_FEATURES + [TEXT_FEATURE]
    X = df[feature_cols]
    y = df[TARGET]

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, stratify=y, random_state=RANDOM_STATE
    )
    print(f"Train: {len(X_train):,}  Test: {len(X_test):,}\n")

    # Evaluate two configurations × three classifiers each.
    classifiers = build_classifiers()
    all_results: dict = {}

    print("=" * 80)
    print(f"{'Configuration':<28} {'Model':<22} {'Prec':>6} {'Rec':>6} {'F1':>6} {'AUC':>6}")
    print("=" * 80)

    for config_name, include_text in [("Numeric only", False), ("Numeric + TF-IDF", True)]:
        for clf_name, clf in build_classifiers().items():
            # HistGradientBoosting does not accept sparse input from TfidfVectorizer.
            # Skip it for the text config; LR and RF illustrate the comparison adequately.
            if include_text and clf_name == "Gradient Boosting":
                continue
            pipeline = Pipeline(
                [("preprocess", build_preprocessor(include_text)), ("clf", clf)]
            )
            pipeline.fit(X_train, y_train)
            metrics, y_proba = evaluate(pipeline, X_test, y_test)
            label = f"[{config_name}] {clf_name}"
            all_results[label] = {
                "pipeline": pipeline,
                "metrics": metrics,
                "y_proba": y_proba,
                "config": config_name,
                "model": clf_name,
            }
            print(
                f"{config_name:<28} {clf_name:<22} "
                f"{metrics['precision']:>6.3f} {metrics['recall']:>6.3f} "
                f"{metrics['f1']:>6.3f} {metrics['roc_auc']:>6.3f}"
            )

    print("=" * 80)

    # Pick best by ROC-AUC overall.
    best_label = max(all_results.keys(), key=lambda k: all_results[k]["metrics"]["roc_auc"])
    best = all_results[best_label]
    print(f"\nBest overall: {best_label}  (ROC-AUC = {best['metrics']['roc_auc']:.3f})\n")

    y_pred_best = best["pipeline"].predict(X_test)
    print("Detailed classification report (best model):")
    print(
        classification_report(y_test, y_pred_best, target_names=["Legitimate", "Fraudulent"])
    )

    os.makedirs(os.path.dirname(MODEL_PATH), exist_ok=True)
    joblib.dump(best["pipeline"], MODEL_PATH)
    print(f"Saved model -> {MODEL_PATH}")

    # Summary JSON for thesis.
    summary = {
        "best_label": best_label,
        "best_model": best["model"],
        "best_config": best["config"],
        "comparison": {
            label: {k: v for k, v in r["metrics"].items() if k != "confusion_matrix"}
            for label, r in all_results.items()
        },
        "best_confusion_matrix": best["metrics"]["confusion_matrix"],
        "feature_set": {
            "numeric": NUMERIC_FEATURES,
            "categorical": CATEGORICAL_FEATURES,
            "text": TEXT_FEATURE,
            "tfidf_max_features": 500,
            "tfidf_ngram_range": [1, 2],
        },
        "n_train": int(len(X_train)),
        "n_test": int(len(X_test)),
        "positive_class_rate": float(y.mean()),
    }
    with open(METRICS_PATH, "w") as f:
        json.dump(summary, f, indent=2)
    print(f"Saved metrics  -> {METRICS_PATH}")

    # Plots.
    os.makedirs(PLOTS_DIR, exist_ok=True)
    plot_roc_curves(all_results, y_test, os.path.join(PLOTS_DIR, "fraud_roc_curves.png"))
    plot_confusion(
        best["metrics"]["confusion_matrix"], best_label,
        os.path.join(PLOTS_DIR, "fraud_confusion_matrix.png"),
    )
    print(f"Saved plots    -> {PLOTS_DIR}/")
    print("\nDone.")


if __name__ == "__main__":
    main()
